"""Adds indexes

Revision ID: 7006cdbde63b
Revises: b4b43ef8b170
Create Date: 2023-06-09 18:40:03.907548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7006cdbde63b"
down_revision = "b4b43ef8b170"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("athletes", sa.Column("event_name", sa.String(), nullable=True))
    op.create_index(op.f("ix_athletes_bib"), "athletes", ["bib"], unique=False)
    op.create_index(
        op.f("ix_athletes_event_name"), "athletes", ["event_name"], unique=False
    )
    op.create_index(op.f("ix_events_name"), "events", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_name"), table_name="events")
    op.drop_index(op.f("ix_athletes_event_name"), table_name="athletes")
    op.drop_index(op.f("ix_athletes_bib"), table_name="athletes")
    op.drop_column("athletes", "event_name")
    # ### end Alembic commands ###
